name: Deploy Next.js site to Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install pnpm
        run: |
          npm install -g pnpm
          pnpm --version

      - name: Install Dependencies
        run: pnpm install
        working-directory: .

      - name: Build with Next.js
        run: pnpm run build
        working-directory: .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out

      - name: Use Secrets
        run: |
          # Access the secrets
          FROM_EMAIL=${{ secrets.FROM_EMAIL }}
          RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}
          
          # Now you can use these secrets in your workflow
          echo "FROM_EMAIL: $FROM_EMAIL"
          echo "RESEND_API_KEY: $RESEND_API_KEY"
