name: Deploy Next.js site to Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Set up Environment Secrets
        run: |
          echo "RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}" >> $GITHUB_ENV
          echo "FROM_EMAIL=${{ secrets.FROM_EMAIL }}" >> $GITHUB_ENV
        shell: bash

      - name: Install pnpm
        run: |
          npm install -g pnpm
          pnpm --version

      - name: Install Dependencies
        run: pnpm install
        working-directory: .

      - name: Build with Next.js
        run: pnpm run build
        working-directory: .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          publish_dir: out
          publish_branch: gh-pages
          enable_jekyll: false



