name: Deploy Next.js site to Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install pnpm
        run: |
          npm install -g pnpm
          pnpm --version

      - name: Set up Environment Secrets
        run: |
          echo "RESEND_API_KEY='re_bWBEX3J1_6x4NJugsFY9PavHZtvg7NnUN'" >> $GITHUB_ENV
          echo "FROM_EMAIL='onboarding@resend.dev'" >> $GITHUB_ENV
        shell: bash

      - name: Install Dependencies
        run: pnpm install
        working-directory: .

      - name: Build with Next.js
        run: pnpm run build
        working-directory: .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out
          publish_branch: gh-pages
          enable_jekyll: false
          publish_committer: GitHub <noreply@github.com>
          publish_committer_name: GitHub Actions
          publish_committer_email: actions@github.com

    environment:
      RESEND_API_KEY: ${{ steps.build.outputs.RESEND_API_KEY }}
