name: Deploy Next.js site to Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install pnpm
        run: |
          curl -o- -L https://unpkg.com/@pnpm/self-installer@6.x.js | node - add --global
          export PATH="$PATH:$HOME/.pnpm-global/bin"
          pnpm --version

      - name: Install Dependencies
        run: pnpm install
        working-directory: .

      - name: Build with Next.js
        run: pnpm run build
        working-directory: .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out

